In [1]:
import numpy as np

### Step 1. Create a random pair of (x,y) coordinates with some noise

In [12]:
x=np.arange(10.0)
rng=np.random.default_rng()
y=2*x+5+rng.random(10)
print(x,y)


[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.] [ 5.84725489  7.53574759  9.95912362 11.30599909 13.92921188 15.83501718
 17.93098195 19.12315075 21.15866168 23.43477768]


### Step 2. Design Matrix

In [ ]:
design_matrix=np.array((np.ones(10),x))
print(design_matrix)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]]
2


In [29]:
# Xᵀ
trans=np.transpose(design_matrix)
# XᵀX
matrix_mul=np.matmul(trans,design_matrix)
# (XᵀX)⁻¹
from numpy.linalg import inv
inv(matrix_mul)


LinAlgError: Singular matrix